package com.model.entity;
// Generated Mar 13, 2017 4:22:05 PM by Hibernate Tools 4.3.1

import java.util.Comparator;
import java.util.Date;




/**
 * DataTable generated by hbm2java
 */
public class DataTable  implements java.io.Serializable{


     private Integer id;
     private Date timestamp;
     private int heatindex;
     private int eggproduction;

    public DataTable() {
    }

    public DataTable(int heatindex, int eggproduction) {
       this.heatindex = heatindex;
       this.eggproduction = eggproduction;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public int getHeatindex() {
        return this.heatindex;
    }
    
    public void setHeatindex(int heatindex) {
        this.heatindex = heatindex;
    }
    public int getEggproduction() {
        return this.eggproduction;
    }
    
    public void setEggproduction(int eggproduction) {
        this.eggproduction = eggproduction;
    }

    public static Comparator<DataTable> dataTableSorting = new Comparator<DataTable>() {

	public int compare(DataTable d1, DataTable d2) {
	   Integer data1 = d1.getId();
	   Integer data2 = d2.getId();
	   //ascending order
	   return data1.compareTo(data2);
    }};


}


